### PR TITLE
feat: move from MathJax to Katex

### PR DESCRIPTION
**Pull request by iisakkirotko**

### CODE REVIEW

**Comment by iisakkirotko** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/widgetti/solara/483?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #479** <a href="https://app.graphite.dev/github/pr/widgetti/solara/479?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #481** <a href="https://app.graphite.dev/github/pr/widgetti/solara/481?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #480** <a href="https://app.graphite.dev/github/pr/widgetti/solara/480?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #483** <a href="https://app.graphite.dev/github/pr/widgetti/solara/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/483?utm_source=stack-comment).

**Comment by maartenbreddels** [comment]
Please take a look at the merge conflicts, I guess it's that node typing line
What are the implications for bundle size? Is this an improvement?

And what are the top reasons for moving from mathjax to katex? I know @kolibril13 is a katex fan as well, maybe he also knows good reasons to switch.

**Comment by kolibril13** [comment]
katex got recommended to me by a friend, it's supposed to be fastest then mathjax.
https://katex.org/
I've never used it in a project before, so I cannot say much more about it.

**Comment by iisakkirotko** [comment]
The benefit of KaTeX is mainly package size, compared to MathJax, which we used previously. Looking at the unpackaged size of the two on npm, you can see that the size of `mathjax-full`, which we use now, is ~34MB, while the size of KaTeX is ~4MB.

As @kolibril13 said, KaTeX seems to be faster than MathJax, but I think in comparison to MathJax 3, the difference is pretty minimal. Note that Jupyter still uses MathJax 2, which is much slower.

**Pull request merged**
