### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by giswqs**
This PR fixes many typos detected by [codespell](https://github.com/codespell-project/codespell). The changes only affect plain text. No Python source code has been changed.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thank you! I felt like i should have done this a long time ago. I've now added this to GHA

**Comment by giswqs** [comment]
There are a couple more errors in some files with non-English text in it. I did not correct them. You might need to exclude those words in codespell. 

image

**Comment by giswqs** [comment]
Something like this if those words are not errors:

```bash
codespell --ignore-words-list="convertor,prolem,ore"
```

**Comment by maartenbreddels** [comment]
Thanks for starting this!

**Pull request merged**
