### PR TITLE
docs: remove `cancelled` arg from work function

### PR DESCRIPTION
**Pull request by Jhsmit**
Assuming this is no longer needed

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks, always embarrassing when CI fails on an unrelated issue :)

**Comment by Jhsmit** [comment]
hmm isnt this setting supposed to fix that?
Otherwise all external PRs would always fail
image

**Comment by maartenbreddels** [comment]
Where do you see that setting?

**Comment by Jhsmit** [comment]
I think only I can see it as contributer of a PR
But it looks like it reveals my secret rather than yours
Still, wouldnt it make sense that since we are on widgetti/solara that the PR has access to GitHub secrets?

**Comment by maartenbreddels** [comment]
No, because that would allow anyone to add `echo $SOME_SECRET` to our CI, and steal our secrets :)

**Comment by maartenbreddels** [comment]
Sorry for all the noise, and thanks you for testing our CI pipeline for PR's :)

**Pull request merged**
