### PR TITLE
feat: add InputTextArea component

### PR DESCRIPTION
**Pull request by alonsosilvaallende**
Fixes https://github.com/widgetti/solara/issues/343

Raw string is required. Otherwise it doesn't accept new characters.

### CODE REVIEW

**Review by iisakkirotko — APPROVED** [review]
Thanks a lot for the contribution @alonsosilvaallende!

**Comment by maartenbreddels** [comment]
Thanks @alonsosilvaallende !

@iisakkirotko Wish we had a link to preview this on pycafe :)

**Comment by maartenbreddels** [comment]
> Raw string is required. Otherwise it doesn't accept new characters.

What do you mean by this?

**Comment by alonsosilvaallende** [comment]
> > Raw string is required. Otherwise it doesn't accept new characters.
> 
> 
> 
> What do you mean by this?

I refer to this r" " part.
image

**Comment by maartenbreddels** [comment]
Awesome work Alonso, thanks !

**Pull request merged**
