### PR TITLE
Minor change in wording also fixing a typo

### PR DESCRIPTION
**Pull request by deeplook**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thank you. I don't think we really use this file anymore. I think we should delete it. Do you want to do that?

**Comment by deeplook** [comment]
It's used here here in the Page class. Should that vanish, too? https://github.com/widgetti/solara/blob/master/solara/website/pages/__init__.py#L13

**Comment by maartenbreddels** [comment]
Best is to replace it by this for the moment. 
```python
@solara.component
def Page():
    solara.Markdown("should not see me")
```

**Comment by deeplook** [comment]
Maybe that's not enough with an integration test giving this: `waiting for locator("text=Test in solara") to be visible`.

**Comment by maartenbreddels** [comment]
Thank you!

**Pull request merged**
