### PR TITLE
fix: FileBrowser bug when navigating to path root

### LINKED ISSUE #688: FileBrowser bug when navigating to path root
Steps to reproduce:

- create an app with `solara.FileBrowser()`
- the Filebrowser starts in the cwd (C:\Users\...), in the app click '..' until you are at 'C'

The filebrowser now shows the as if it was in the cwd instead of disk root

Similar issue when using eg `solara.FileBrowser(directory="D:\\")`

 FileBrowser starts at D:\ correctly
click to enter 'my_folder'
image
click '..' to go back
image
note the lacking trailing backslash
click 'my_folder' again
image
now backslash is missing

click '..' again:
image

This is on windows and solara 1.33.0

### PR DESCRIPTION
**Pull request by Jhsmit**
Fixes #688 

The PR changes the type of paths used internally in `FileBrowser` from `str` to `pathlib.Path` such that the correct parent is always returned.

Also fixed optional kwargs typing

### CODE REVIEW

**Comment by Jhsmit** [comment]
I have a use case where I want to run an app on a server and show files/folders on the server in a given directory. 

However, the user should not be able to navigate to parent directories above the starting directory. 

I've currently implemented it as:

```python
@solara.component
def Page():
    my_dir = Path.cwd()

    def browser_filter(path: Path) -> bool:
        if path.is_dir():
            return path not in my_dir.parents
        return True

    MyFileBrowser(directory=my_dir, directory_first=True, filter=browser_filter)
```

Which then requires an additional check on `new_dir` in `FileBrowser`

```python
            new_dir = current_dir.value.parent
            if not filter(new_dir):
                return

```

I can add this to this PR or make another one if you think it would be more generally useful.

**Comment by maartenbreddels** [comment]
beautifull fix!
Regarding your last comment, does this solve your problem:
https://github.com/widgetti/solara/issues/149
(why is there no pycafe example? :))

**Comment by Jhsmit** [comment]
here is the link to [pycafe](https://py.cafe/snippet/solara/v1#c=H4sIAL6OjmYAA3VWW2_bNhT-K577kgKVYMmOLwEErC067GkotmEvTVFQFGUxlkiFpOyoRf_7vnMkK3bapmgQnvv5zk3f5tIWan43101rXZh5Wwsn7t29KZ1tZq0IVa3z2cj9iCfx6P-7t_98-PLx7b9_zjKmx_JU3Lw-c38fDMXSQtMoE4hYqBKie3Xz-o6eM_wU2ikZrOthZVTpvPrilJBBH9XN5IUtk0ajvIeNX8j_BWeTKPlrnQ3wcOHyzJGVkocvuYA6pXlzFHWnrsXoR5czYwFMcKNE7INwwZ80dIj6HOKPylcpxqyPwCeNn4mP-U3C9_P3wlAEhZ2FSoTf7ucv1VTt1U9dv7RF6FzKORU6Zy4i9F3updO5unmBzoTpBeiqLAnZEeGp9BdSf-havXP25JW7mZxMpoDsVYBXKYwWPjhn3c2V2ORo_mbu1GMHuw0azKOJx-4lTuhbauuBgrdo2_-0Os3vSgG03sxVocMHI_IaUsF1oLR9qKyBTtvbQhcqOi7i9DZOoFyL3nZhfvdt7qwNf1uY-Xb2gPQgIStdF05B_dPECSL3KvyaCQ5BiweCi9t-_v0z_n1_My8BG9L59BmerTzQ8701AUlC9tWsEr66mxWL9Xah0l2Sr9KkFPk6L5LlNlmsVtt0e7sp740wvbZZtopX8QIvt7cmjWRZ6ixLl3Hyghjl2hTa7D24SZzGi9mrWQPvJIQcsyyJl6ziQ7AHZUgOlhNQQnD0Gm3mQh6kqOssA35MUKILuuxqb7t2RQElaZyCXmNqqyxbxwsSk3ioYG0NW7fwBctSOShSvAtY38QptIYEkjhBafCqhAPIkbGuEbX-qlyWLaFMgrWWhyzbIqoNXrZphojAKlTe7duezIA9JVooaZ1Aj1IA8MAbC51ePDWczYZI6klJpGP2lP-CKCUgefDWeMTfCCKnnBDVjepHESHaFSiPhSGnHHqVJGQ04epUXSMMwmd0WFsXBraWpKbb_qCcUQhiTS2JDECibuX01mRtJER7ZRAdYTiiD8axg13kwykNb8DK6e9G-ydd7FWAFsG1BMnbogMWmnwgHejC1gOmhmPe8UubB5FydhQSQdBajT7lGnASl7AgsQ2ZfugQqnIR6oOOJo9I6oJsHaK9pWo_E9WRJpxcry9NYK8cyVvKmE11vGZH-LPRBmNP-uisSaAWedT2e94exOP-vuBNoFA2CbBrhDsU9gRIlvH6-RnpADtT0kTuWi9K5IHIyGEjQlvbgFMaaVNrAw4sUl82gJmbizFstA8dcckU3iaXtfBeS67fRYrEGOCDJnsFxRqkCxL6dE11NXlJYwEKGm7BFOVDJHxvJG2GBGiSJvZ3bi36dA14LnyM9MhXepwdMtE1w-Sk7MPCpcO2BEob1AzmWmEKK9H8QBHUsdtbzClcLjBwwKNVTy2uATUFWmny2GJisfow0wzQJr4lWl3z-kGWbL4WgdLCPYH11TDQuEGNCpXq_NRWCHeQB6sNES2WgwadkF0B-NbTnBA0u3j7HAHWs7MS92YIgAx0TqEBxbjQyFsvKZ2h81JKbmoi1JvHse0b7gz1hLXtMUWEBCXPvOG-VCG0g00mOo_in0u6Y5SGkS5EUEOsKQywf6bTcEW13e-HQBAusXpBy4p2Klv92jyCiR1zATN_LdFg0_qDH7qiaAwOf8mD7kq5XC53EbLWcE8bkToU9SbObrt-yYEvp2mZJ7SnxxfVgtbf2U1beJ4TKGwvwvHKFGlwuGqTKFZ61463YE0rCVl7_cRTwD3rjcYd4B7mSzHceX7yTRre04J4Qe74gpxJmFWNBTPdM3zfyQOhDnvjwqFPvlqFwG255L06bpWCmxr5QBFXoZfeYyWOtxLwDBI8KkhRB1jh-4a1D7v0MUCY_FBnTAX6N10tlgkWDcRwcK6aaTXA3DmN_dbQUPCOZ7fYKNg0y2H70PuosVVRb8TObXESQVaFxQm7bgym89cH9-XlwjlJbMOACnG_IvSTwsKpLV_-1bBIQFI4tONXBO1a8qVyDwu40efJpBoP0gODRoMhHfctPhjOiQ4B0ur1vsavx1oHBefz7_8DBvNIC7kMAAA)

the fix in the issue you mention does indeed work. 

However, given that the function of `filter` is to filter out files and/or folders that should not be shown, wouldn't it make sense to pass the new parent folder through filter first before navigating there?
ie you could consider it to be a bug that `filter` is not respected when navigating up

**Comment by maartenbreddels** [comment]
I don't think I fully understand the problem, can you show an example that does not work?

**Comment by Jhsmit** [comment]
```python
import solara
from pathlib import Path

BASE_PATH = Path.cwd()

@solara.component
def Page():
    directory = solara.use_reactive(BASE_PATH)
    def protect_filter(path: Path) -> bool:
        if path.is_dir():
            return path not in BASE_PATH.parents
        return True

    solara.FileBrowser(directory, filter=protect_filter)
```
[pycafe](https://py.cafe/snippet/solara/v1#c=H4sIAHaTjmYAA3VWbW_bNhD-K4L6JQUiwZIcvwTQsHbosI_FVuxLWwSURNuMJVIhqThqkf--546y4mRbira5O9773XP6GdemkfFtrLreWB850worvtlvemdNF_XCH1pVRZP0M0iS0d-PH_76dPf5w5c_opL5aX1qrt6fpb8GQ2ltoKml9sRs5A5P9_Lq_S2REX4aZWXtjR1hZVIZnLyzUtRePcqr2QtbZg0Y6a3xULvbqdZLe0VR3nIQ76Pkl6gypp0d0I-CBkWo3B38XXg__1jpB6v5UaSNj5SOZsdpLyzid5c60_svdpDnhIk9JfC7auVHa04Ooc35XUch2PJ17HNa9H98HVv5MEClI4_oytQOkvixpz4FDmjR938reYpvd6J18jqWjfKftKhavPII7DruR38wGjr9aBrVyORxkeY3aQblVoxm8PHtz9ga4_80MPPz7AGR40V9UG2DxOPbr7PEi8pJ__9CSKiEIBBc2o_x8_V_iy-zTP2Tj5-_48_zdYyiSOT99TtCNPWRyN-M9ngHrXfRQTg0ulmsNguZb7NqmWc7Ua2qJis22WK53OSbm_XumxZ6VKYsl-kyXYCye6PzpN7tVFnmRZq9YSaV0o3SewdplubpInoXdfBOj1CMsszSglWc9-YoNb2D5Qwc7y1Rk81K1MdatG1ZotDMkGLwaje0zgz9kgLK8jQHv8V8H8pylS7oWQ1CekwtbN3AFyzX0kKR4l3A-jrNoRUSyNIMPQR1EBbdSLSxnWjVD4xWWUCZHraqPpblBlGtQZmuCxFB1Mhq2PcjmYF4TrSRtbECc0oBwAPvKhaxeeo4mzWx5JOskY7eU_4L4uxQkntntEP8nSB2zglR36h_FBGiXYLz0GhyyqEfsoyMZtydw9AJjfC5OqytGg1bBampfjxKqyWCWNHsIgOwaKw5vRVZmxjJXmpERzWcqg_B4wC7yIdTCjTKyulvJ_sn1eylhxaVqwDLmWZALRT5QDrQha17rBfHvGVK6XuRc3YUEpWgNwpzyj3gJC7LgsTWZPp-QKjSJugPJpo8IqkLtrGI9oa6_cKUj7Qk5Hp1aQLY8kjecq7Z3MfX4gS_dkoDH0gfkzU_aEWV9OOeF5BkPN8XsrkolE2G2nXCHhtzQkmKdPVCJsrDzpw0sYfeiR3yQGTksBO-b43HEUmUbpWGBBZpLjuUmYeLa9gp5weSkinQuqpb4ZyquX8XKZIglA-a7BUco5EuWJjTFfVVVztaC3AwcAvmSOcT4UZdEzJkqCZpAopxLTCnK5TnwsfET9xBTbtDJoYubE7OPgxcWsAqqrRGz2CuF7oxdQB2cKdpx_1wcLnAwqEevXzqAf80FBil2WOPjQX0Yae5QOv0hnhty_CDLNl8KzylhZsC68uw0DgnnfQHObh5rBBueA9R7xMClqMCnyq7ROF7R3tCpdmmm5cIANTW1NLxQIR8BisxgGICNPI21pROmLyckpuHCP3mdezHjidDPgG2HbaIKkHJsywcooP3fbDJTOvQ_HNLt1ylsNKN8DLEmsMA-2c-LVfSmv0-BIJwSTQKAivCVLb6o3uAEBhzUWb-rqDFJviDHzpEGAwOv-BFt7u6KIptgqwV3BMi0oSi3yTZblZvJfBlFYF5Rjg9UdQLgr-zm75xvCdQ2FyE46Rucm9x1eangPShn27BiiAJWTv1xFvAM-u0wh3gGeZLET4ImOSbFOgZIN6wB74gZxZ2VQFg5nvmPC4YVR32JsABy7bSex7LgnF1QpWGhxr5QBFXYaydAyROtxLlCS94VZCi8rDC9w2wD7v0WUA1-VefsRWY33y5KDIADZ7h4LwapmUo82AV8K2jpWCMZ7dAFCBNEdCH6EcFVEW_ETuPxUn4-tAYnLDXg8F8_vrgubwEnFMNNPToEM8rQj9JAE5r-PIvA5CAJXFop68IwlryJSsHC7jR582kHofXQUCrwSWd8BYfDOdEQ4AEvc61-OehVV7Cefz8D9G0z-OzCwAA)

In this example, based on how you interpret the docstring of `filter`, you might expect this filter to make it impossible to navigate up above `BASE_PATH`. But you can access it if you click '..', you just cannot go back. This would be 'fixed' when adding the early return when filter returns `False` (`if not filter(new_dir):`)

**Pull request merged**
