### PR TITLE
fix: app hangs on starlette when sufficiently many cookies are set

### PR DESCRIPTION
**Pull request by iisakkirotko**
Couldn't reproduce locally. Giving ci a shot.

### CODE REVIEW

**Comment by iisakkirotko** [comment]
* **#751** <a href="https://app.graphite.dev/github/pr/widgetti/solara/751?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @iisakkirotko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by maartenbreddels** [comment]
image

From https://github.com/widgetti/solara/actions/runs/10484645065/job/29169659662?pr=743


I added branch protection so we can auto merge, but that didn't let us do the auto commit. I had to disable it, so the updates ran on master. Maybe that was the same issue? 

@EwoutH could you try to open a new trivial PR so we can test this?

**Comment by EwoutH** [comment]
> @EwoutH could you try to open a new trivial PR so we can test this?

Of course, but I now see CI passing, so is it still needed?

**Comment by iisakkirotko** [comment]
Hey @EwoutH! You're right, this issue turned out to be unrelated. I'll ping you to test stuff when I get around to working on https://github.com/widgetti/solara/issues/750 :)

**Comment by maartenbreddels** [comment]
Thanks @iisakkirotko !

Sorry, I misunderstoof @EwoutH , it seems 3 (!) related issues were confused in my mind

**Pull request merged**
