### PR TITLE
adds ploomber cloud as hosted option

### PR DESCRIPTION
**Pull request by edublancas**
as discussed with @maartenbreddels, I'm adding Ploomber Cloud as a hosted option to the docs.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Great, thank you @edublancas !

**Comment by edublancas** [comment]
thanks, @maartenbreddels!

are the docs deployed on each stable release? I wanted to share this in our socials, but I couldn't find the change in the docs: https://solara.dev/docs/deploying/cloud-hosted so my guess it'll be out until the next solara release

**Comment by maartenbreddels** [comment]
I just did an extra deploy, it's live :)

**Comment by edublancas** [comment]
@itepifanio: a few users already requested this feature, so we're prioritizing it! I'll get back to you once we have something working.

**Comment by edublancas** [comment]
@itepifanio CLI/GitHub deployment is out now: https://docs.cloud.ploomber.io/en/latest/user-guide/cli.html

please give it a try and share your feedback!

please be gentle with API calls; we're still testing this out. we'll make a public announcement early next week!

**Comment by itepifanio** [comment]
> please give it a try and share your feedback!

@edublancas it works really well. Congrats on the docs, are very easy to follow!

**Comment by edublancas** [comment]
@itepifanio I'm glad to hear it worked well! feel free to reach out if you encounter any issues or if you have feedback!

**Pull request merged**
