### PR TITLE
feat: support ipwidgets v8

### PR DESCRIPTION
**Pull request by maartenbreddels**
Although in the frontend we still use ipywidgets v7, most thing we do
do not care about this.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I just noticed this today, because i was fixing ipyvolume to work in ipywidgets. Let me see if I can rebase this PR, and see if I can find the issue.

**Comment by maartenbreddels** [comment]
Note, this also requires:
```
$ (cd packages/solara-widget-manager; npm instal; npm run build)
$ (cd packages/solara-vuetify-app; npm instal; npm run build; npm run devlink)
```

**Comment by maartenbreddels** [comment]
Make sure to clear your browser cache, because if we don't change the version number during dev, the browser will pick up the cached version (Dev console -> Network -> Disable cache in chrome)

**Comment by mangecoeur** [comment]
Thanks, I give this a go on Friday but I didn't quite get it working even following your instructions, but that might have been more end-of-the week brain fade problems ;)

**Pull request merged**
