### PR TITLE
ci: run pre commit in ci for code quality

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Instead of manually keeping pre-commit versions in sync with CI, lets also use pre-commit in CI

**Comment by maartenbreddels** [comment]
Giving up for now, I have no idea why isort under Python 3.9 decides to reorder imports.

**Comment by maartenbreddels** [comment]
After d15ec01a36b8a08a2eacead857a3ba36bace1352 it seems that we cannot install isort on Python 3.7 anymore. Might be a clue that the isort on 3.9 in pre commit does not respect the version number in the pre commit file.

**Comment by iisakkirotko** [comment]
superseded by https://github.com/widgetti/solara/commit/0b5b6090b6f95be5baa7f254a5bceb9203abb469

**Pull request closed without merging**
