### PR TITLE
fix: cap pydantic < 2.0

### PR DESCRIPTION
**Pull request by lp9052**
due to pydantic breaking change.

see #187

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I agree, we first merge this, get CI green and see if we can get it working with 2 very soon, or do a release with a cap (I hate caps, so I prefer not to release with it :P)

**Comment by maartenbreddels** [comment]
Thanks!

**Comment by lp9052** [comment]
Ouch. Thanks for deduplicate it. Can't believe I made this mistake. Should we alphabetically sort the dependencies list. To avoid future issue like this.

**Comment by maartenbreddels** [comment]
Np 🙂
I prefer as little changes as possible to make it easier to track changes, but if it bothers you a lot, a single sort pr is ok.
I should have sorted it from the beginning…

**Pull request merged**
