### PR TITLE
fix: test and avoid memory leaks by checking references to virtual kernel

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Current dependencies on/for this PR:
* master
  * **PR #377** <a href="https://app.graphite.dev/github/pr/widgetti/solara/377?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/377?utm_source=stack-comment).

**Comment by maartenbreddels** [comment]
I manually changed the branch we will merge this to, so it does not depend on #377 anymore. @iisakkirotko can you fix this,or should we just merge this as is? (squashed)

**Comment by iisakkirotko** [comment]
I changed the base branch to master in graphite, is there anything else that I should do? I also opened https://github.com/widgetti/solara/pull/936 to debug the CI issue related to this, so from that side we're clear to merge 👍

**Comment by maartenbreddels** [comment]
Nice, thanks for opening that PR!

**Pull request merged**
