### PR TITLE
fix: remove pydantic

### PR DESCRIPTION
**Pull request by lp9052**
testing migrate to pydantic 2.0

where pydantic_settings is seperate package see #187

I quickly changed everything to pedantic_settings. But Solara depends on vaex which still error out.

I think for now we shall cap pedantic version. @maartenbreddels

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Ok, this is not as simple as I hoped, see https://github.com/pydantic/pydantic/discussions/6497 

Let's try to get of pydantic. We simply need an easy way to configure things, it shouldn't cause installation issues or breakage.

**Comment by maartenbreddels** [comment]
Thanks for starting this. In the end, we had to remove Pydantic, otherwise we'd have to choose between v1 and v2 and we don't want to do that for our users.

**Comment by lp9052** [comment]
Sorry for the delay, I was preparing my PhD application. It's unfortunate that we have to adopt this internally. Their decision to make a big change in a popular package is baffling. It's basically ineffective until everyone switches to pydantic2. I was dinged about our failing builds this morning, so I'm glad this was addressed. I truly appreciate it.

**Comment by rht** [comment]
Thank you for shipping this!

**Pull request merged**
