### PR TITLE
fix[docs]: wide outputs of jupyter notebook based tutorials overflowing width limit"

### PR DESCRIPTION
**Pull request by iisakkirotko**

### CODE REVIEW

**Comment by iisakkirotko** [comment]
* **#625** <a href="https://app.graphite.dev/github/pr/widgetti/solara/625?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#624** <a href="https://app.graphite.dev/github/pr/widgetti/solara/624?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @iisakkirotko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by mariobuikhuizen** [comment]
Is this also a good width for mobile?

**Comment by iisakkirotko** [comment]
@mariobuikhuizen It's not perfect for mobile, but it's only a `max-width`, so given that any content adapts to mobile width (spoiler: it doesn't always, but I think that's a separate issue to be solved in a refactor) it should also adapt

**Review by mariobuikhuizen — APPROVED** [review]

**Comment by iisakkirotko** [comment]
### Merge activity

* **May 1, 10:24 AM EDT**: @iisakkirotko started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/widgetti/solara/624).

**Pull request merged**
