### PR TITLE
CI: Run workflows once a week

### PR DESCRIPTION
**Pull request by EwoutH**
Adds a weekly scheduled run to all CI workflows which run on push or PR, which now run each Monday at 06:00 UTC.

A periodically scheduled run can detect errors and warnings appearing in changes in upstream dependencies or the build environment. By having a scheduled run they can be traced back easier to a dependency or environment change, then if they would pop up in a random PR.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thank you!
Note that we have bigger plans along the lines or https://github.com/widgetti/ipyaggrid/issues/44#issuecomment-1689710768 but I think this is indeed a good improvement.
Although I think once a week is maybe not often enough. What about every day? Or twice a week?

**Comment by EwoutH** [comment]
Thanks for getting back! Since these workflows also run on every push to the main branch and on every PR, I think two additional runs a weeks should be more than enough. It’s more to have some recent reference run in periods of inactivity.

**Comment by maartenbreddels** [comment]
Could you add comments to the cron lines? I've never met someone in my life (except chatgpt) who knows by heart what it means. :)

**Comment by EwoutH** [comment]
Yes, will do!

I always use https://crontab.guru/ by the way, I find it really useful.

**Comment by maartenbreddels** [comment]
Dankjewel Ewout!

**Comment by EwoutH** [comment]
Graag gedaan!

**Comment by EwoutH** [comment]
The first scheduled runs where queued and performed [as expected](https://github.com/widgetti/solara/actions?query=event%3Aschedule).

Screenshot_203

**Comment by maartenbreddels** [comment]
Love it ❤️ ! Thank you

**Pull request merged**
